### ISSUE TITLE
[BUG] Unicode characters not matching

### ISSUE THREAD

**Issue by bilaalrashid** [eskriett/confusables#4]
I have identified these following characters (upper and lowercase), which do not trigger a match:
```
𝐴𝐵𝐷𝐸𝐺𝐻𝐾𝑀𝑁𝑂𝑃𝑅𝑆𝑇𝑈
𝑎𝑏𝑐𝑑𝑒𝑓𝑔𝑖𝑙𝑚𝑛𝑜𝑡𝑤𝑥
```

**Comment by eskriett** [comment]
These look to be working with the latest tables.
